# Default values for omec-upf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Configure process namespace sharing for pod
shareProcessNamespace: true

## Service of omec upf
service:
  # -- Specifies the type of service to deploy
  type: NodePort
  # -- Specifies the port of service
  port: 80
  # -- Specifies the nodePort of service if the service type is NodePort
  nodePort: 30020

## Service of omec upf
serviceMetrics:
  # -- Specifies the type of service to deploy
  type: ClusterIP
  # -- Specifies the port of service
  port: 8080
  # -- Specifies the nodePort of service if the service type is NodePort
  nodePort: 30022

## Service account for omec-upf to use.
##
serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  #
  create: false
  # -- (object) Additional custom annotations for the ServiceAccount
  #
  annotations: {}
  # -- (string) The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  #
  name: ""

## RBAC Configuration
rbac:
  # -- Specifies whether a cluster role binding should be created
  create: false
  # -- The cluster role name
  clusterRole: "cluster-admin"

## Service Monitor Configuration for operated Prometheus
serviceMonitor:
  # -- Specify if service monitor will be created
  create: true
  # -- Specify the namespace for the service monitor
  monitoringNamespace: monitoring
  # -- Specify extra monitoring labels for the service monitor
  monitoringLabels:
    release: k8s-prom
  # -- Specify the time scrape interval
  scrapeInterval: 5s
  # -- Specify the scrape timeout
  scrapeTimeout: 5s


## UPF network configuration
upf:
  # -- Number of workers as string to assign for queue handling on each port
  num_workers: "4"
  ## s1u network configuration
  s1u:
    # -- s1u gateway interface name
    iface: net0
    # -- s1u MAC addresses of gateway interface
    mac: 9e:b2:d3:34:cc:28
    # -- s1u ip address
    ip: 198.18.0.1/30
    # -- s1u static ip address of its neighbor of gateway interface
    nhip: 198.18.0.2
    # -- s1u static MAC addresses of the neighbor of gateway interface
    nhmac: 22:53:7a:15:58:50
    # -- s1u IPv4 route table entry in cidr format
    route: 11.1.1.128/25
    # -- s1u pci environment variable name
    pci: PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK_B2B_NET1
  ## sgi network configuration
  sgi: 
    # -- sgi gateway interface name
    iface: net1
    # -- sgi MAC addresses of gateway interface
    mac: c2:9c:55:d4:8a:1f
    # -- sgi ip address
    ip: 198.19.0.1/30
    # -- sgi static ip address of its neighbor of gateway interface
    nhip: 198.19.0.2
    # -- sgi static MAC addresses of the neighbor of gateway interface
    nhmac: 22:53:7a:15:58:50
    # -- sgi IPv4 route table entry in cidr format
    route: 0.0.0.0/0
    # -- s1u sgi environment variable name
    pci: PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK_B2B_NET1


## Configuration for bessd container
bessd:
  ## Image configuration
  image:
    # -- bessd image repository
    repository: nfvri/upf-epc-8806-bess
    # -- bessd image pull policy
    pullPolicy: IfNotPresent
    # -- bessd image tag
    tag: "0.3.0-dev"

  # -- Override default container command (useful when using custom images or configmaps)
  command: []
  # -- Path of upf conf file. Populates the CONF_FILE env variable of bessd container. Default to /opt/bess/bessctl/conf/upf.json
  upfConfFile: /opt/bess/bessctl/conf/upf.json

  # -- (object) Security Context Configuration
  securityContext:
    capabilities:
      add:
      - NET_ADMIN
      - IPC_LOCK
  ##  Resources configuration of bessd
  resources:
    # -- The resources requests for the bessd container
    requests:
      cpu: "6000m"
      memory: "2Gi"
      hugepages-1Gi: 4Gi
    #  intel.com/intel_sriov_dpdk_b2b_net1: '1'
    #  intel.com/intel_sriov_dpdk_b2b_net2: '1'
    # -- The resources limits for the bessd container
    limits:
      cpu: "6000m"
      memory: "2Gi"
      hugepages-1Gi: 4Gi
    #  intel.com/intel_sriov_dpdk_b2b_net1: '1'
    #  intel.com/intel_sriov_dpdk_b2b_net2: '1'

  # -- (object) OMEC UPF bessd container's readiness probe
  readinessProbe:
    tcpSocket:
      port: 10514
    initialDelaySeconds: 30
    periodSeconds: 20
  # -- (object) OMEC UPF bessd container's liveness probe
  livenessProbe:
    tcpSocket:
      port: 10514
    initialDelaySeconds: 30
    periodSeconds: 20  

  # -- (array) A list of volume mounts to be added to the bessd container
  extraVolumeMounts: []

## Configuration for web container
web:
  ## Image configuration
  image:
    # -- web image repository
    repository: nfvri/upf-epc-8806-bess
    # -- web image pull policy
    pullPolicy: IfNotPresent
    # -- web image tag
    tag: "0.3.0-dev"

  # -- Override default container command (useful when using custom images or configmaps)
  command: []

  # -- (object) OMEC UPF web container's readiness probe
  readinessProbe: {}
  # -- (object) OMEC UPF web container's liveness probe
  livenessProbe: {}
  ##  Resources configuration of web
  resources:
    # -- The resources requests for the web container
    limits:
      cpu: 1000m
      memory: 512Mi

  # -- (array) A list of volume mounts to be added to the web container
  extraVolumeMounts: []

## Configuration for routectl container
routectl:
  ## Image configuration
  image:
    # -- routectl image repository
    repository: nfvri/upf-epc-8806-bess
    # -- routectl image pull policy
    pullPolicy: IfNotPresent
    # -- routectl image tag
    tag: "0.3.0-dev"

  # -- Override default container command (useful when using custom images or configmaps)
  command: []

  # -- (object) Security Context Configuration
  securityContext: {}

  # -- (object) OMEC UPF routectl container's readiness probe
  readinessProbe: {}
  # -- (object) OMEC UPF routectl container's liveness probe
  livenessProbe: {}
  
  ## Resources configuration of routectl
  resources:
    # -- The resources requests for the routectl container  
    limits:
      cpu: 1000m
      memory: 512Mi

  # -- (array) A list of volume mounts to be added to the routectl container
  extraVolumeMounts: []

## Configuration for pfcpiface container
pfcpiface:
  ## Image configuration
  image:
    # -- pfcpiface image repository
    repository: nfvri/upf-epc-8806-pfcpiface
    # -- pfcpiface image pull policy
    pullPolicy: IfNotPresent
    # -- pfcpiface image tag
    tag: "0.3.0-dev"

  # -- Override default container command (useful when using custom images or configmaps)
  command: []
  
  # -- (object) OMEC UPF pfcpiface container's readiness probe
  readinessProbe: {}
  # -- (object) OMEC UPF pfcpiface container's liveness probe
  livenessProbe: {}  
  ## Resources configuration of pfcpiface
  resources:
    # -- The resources requests for the pfcpiface container  
    limits:
      cpu: 1000m
      memory: 512Mi

  # -- (array) A list of volume mounts to be added to the pfcpiface container
  extraVolumeMounts: []

# -- (object) podAnnotations Map of annotations to add to the pods
podAnnotations: {}
  # k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net1,default/sriov-dpdk-b2b-net2

# -- (object) Node labels for omec-upf pods assignment
nodeSelector: {}
 # kubernetes.io/hostname: "clx2"

# -- (array) Tolerations for omec-upf pods assignment
tolerations: []

# -- (object)  Affinity for omec-upf pods assignment
affinity: {}

# -- (array) A list of volumes to be added to the pod
extraVolumes: []
