apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.core.podName }}
  labels:
    app: {{ .Values.core.podName }}
  annotations:
    {{ .Values.core.podAnnotations }}
spec:
  shareProcessNamespace: true
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}
  containers:
  - name: {{ .Values.core.podName }}--core
    image: {{ .Values.image }}
    stdin: true
    tty: true
    command: {{ .Values.core.command }}
    securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
    resources:
      {{- toYaml .Values.core.resources | nindent 8 }}
    volumeMounts:
      {{- toYaml .Values.core.volumeMounts | nindent 8 }}
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: pattern-weekly
    configMap:
      name: pattern-weekly
      defaultMode: 0777
  - name: pktgen-premium-core-weekly
    configMap:
      name: pktgen-premium-core-weekly
      defaultMode: 0777
