apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvino-model-server.fullname" . }}
  labels:
    {{- include "openvino-model-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openvino.service.type }}
  ports:
    - port: {{ .Values.openvino.service.restport }}
      targetPort: restport
      protocol: TCP
      name: restport
    - port: {{ .Values.openvino.service.port }}
      targetPort: port
      protocol: TCP
      name: port
  selector:
    {{- include "openvino-model-server.selectorLabels" . | nindent 4 }}
