apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvino-model-server.fullname" . }}
  labels:
    {{- include "openvino-model-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openvino.service.type }}
  ports:
    - port: {{ .Values.openvino.service.ports.port1 }}
      targetPort: 8000
      protocol: TCP
      name: port1
    - port: {{ .Values.openvino.service.ports.port2 }}
      targetPort: 9000
      protocol: TCP
      name: port2
  selector:
    {{- include "openvino-model-server.selectorLabels" . | nindent 4 }}
