# Default values for pktgen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Node labels for node selection
nodeSelector:
    kubernetes.io/hostname: "clx1"

# -- Security configuration
securityContext:
  privileged: false
  capabilities:
    add:
    - IPC_LOCK

image:
  repository: omecproject/upf-epc-bess:master-latest
  pullPolicy: Always

# -- Network configuration
upf:
  s1u: 3a:75:03:3c:7a:19
  sgi: 4e:a6:53:e3:0f:65 

# -- Select true when the user supplies custom traffic pattern, configMap and values override
overideConfigMap: false

# Access Packet generator Configuration
access:
  podName: pktgen-premium-access
  
  command: ["bash", "-xc", "cp /conf/pktgen-premium-access-weekly.bess /opt/bess/bessctl/conf/; bessd -grpc-url=0.0.0.0:10514; sleep 10; ./bessctl run pktgen-premium-access-weekly"]

  podAnnotations:
    k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net1

  # -- Access Packet generator container resources configuration
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net1: '1'
    limits:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net1: '1'

# Core Packets generator configuration
core:
  podName: pktgen-premium-core
  
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net2

  command: ["bash", "-xc", "cp /conf/pktgen-premium-core-weekly.bess /opt/bess/bessctl/conf/; bessd -grpc-url=0.0.0.0:10514; sleep 10; ./bessctl run pktgen-premium-core-weekly"]

  # -- Core Packet generator container resources configuration
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net2: '1'
    limits:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net2: '1'
  
  extraVolumeMounts: []
  
  extraVolumes: []
