# Default values for pktgen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Node labels for node selection
nodeSelector:
    kubernetes.io/hostname: "clx1"

# -- Security configuration
securityContext:
  privileged: False
  capabilities:
    add:
    - IPC_LOCK

image:
  repository: omecproject/upf-epc-bess:master-latest
  pullPolicy: Always

# -- Network configuration
upf:
  s1u: 3a:75:03:3c:7a:19
  sgi: 8e:a9:bb:1e:80:71

# Access Packet generator Configuration
access:
  podName: pktgen-premium-access

  podAnnotations:
    k8s.v1.cni.cncf.io/networks: default /sriov-dpdk-b2b-net1

  # -- Access Packet generator container resources configuration
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net1: '1'
    limits:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net1: '1'

  volumeMounts:
    - name: hugepages
      mountPath: /dev/hugepages
      readOnly: False
    - name: pattern-weekly
      mountPath: /opt/bess/bessctl/conf/patterns/
    - name: pktgen-premium-access-weekly
      mountPath: /conf

# Core Packets generator configuration
core:
  podName: pktgen-premium-core
  
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: default /sriov-dpdk-b2b-net2

  # -- Core Packet generator container resources configuration
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net2: '1'
    limits:
      cpu: "2000m"
      memory: "4Gi"
      hugepages-1Gi: 4Gi
      intel.com/intel_sriov_dpdk_b2b_net2: '1'

  volumeMounts:
  - name: pktgen-premium-core-weekly
    mountPath: /conf
  - name: pattern-weekly
    mountPath: /opt/bess/bessctl/conf/patterns/          
  - name: hugepages
    mountPath: /dev/hugepages