apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tensorflow-serving.fullname" . }}-config
  labels:
    {{- include "tensorflow-serving.labels" . | nindent 4 }}
data: 
  prometheus.txt: |
    {{ .Values.config.prometheusConfig | nindent 6  }}

