apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensorflow-serving.fullname" . }}
  labels:
    {{- include "tensorflow-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcport }}
    targetPort: grpcport
    protocol: TCP
    name: grpcport
  - port: {{ .Values.service.restport }}
    targetPort: restport
    protocol: TCP
    name: restport
  selector:
    {{- include "tensorflow-serving.selectorLabels" . | nindent 4 }}
