{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-benchmark.fullname" . }}-config
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
  labels:
    {{- include "redis-benchmark.labels" . | nindent 4 }}
data:
  {{- if .Values.redis.config }}
  {{- range $configName, $configYaml := .Values.redis.config }}
  {{ $configName }}: |
    {{- if (eq (kindOf $configYaml) "map")}}
    {{-   tpl (toYaml $configYaml) $root | nindent 4 }}
    {{- else -}}
    {{-   tpl $configYaml $root | nindent 4 }}
    {{- end -}}
  {{- end -}}
  {{- else }}
  redis.conf: |

  {{- end }}
