apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-benchmark.fullname" . }}-metrics
  labels:
    {{- include "redis-benchmark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
    - port: {{ .Values.exporter.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
      {{- if eq .Values.exporter.service.tpye "NodePort" }}
      nodePort: {{ .Values.exporter.service.nodePort }}
      {{- end }}
  selector:
    {{- include "redis-benchmark.selectorLabels" . | nindent 4 }}
