version: '3'

services:
  tf-serving:
    image: tensorflow/serving
    container_name: tf-serving
    ports:
      - 8501:8501
    volumes:
      - ./mobile_net_cats:/models/mobile_net_cats
    environment:
      - MODEL_NAME=mobile_net_cats

