{
 "title": "Arcadia dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kube_node_status_condition,job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_status_condition,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Active Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Ready Nodes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Ready Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Total Allocatable Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Allocatable Cpu Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocatable Gpu",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocatable Resources of Active Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Total Allocatable Cpu Cores of Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"cpu\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory of Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"memory\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocatable Gpu of Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"nvidia_com_gpu\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Node Resources Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Cores Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gpu Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"nvidia_com_gpu\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Node Resources Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Cores Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gpu Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"nvidia_com_gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Percentage Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cpu Current Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Current Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gpu Current Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"nvidia_com_gpu\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"nvidia_com_gpu\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Over Time Percentage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Cpu Demand Over Time Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})*100",
     "legendFormat": "CPU demand"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"cpu\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})*100",
     "legendFormat": "CPU availability"
    }
   ]
  },
  {
   "title": "Memory Demand Over Time Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})*100",
     "legendFormat": "Memory demand"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"memory\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})*100",
     "legendFormat": "Memory availability"
    }
   ]
  },
  {
   "title": "Gpu Demand Over Time Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"nvidia_com_gpu\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"nvidia_com_gpu\"})*100",
     "legendFormat": "Gpu demand"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\", resource=\"nvidia_com_gpu\"} * on (node) kube_node_status_condition{condition=\"Ready\",status=\"true\"})/sum(kube_node_status_allocatable{node=~\"$node\",resource=\"nvidia_com_gpu\"})*100",
     "legendFormat": "Gpu availability"
    }
   ]
  },
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "count(count by (pod) (kube_pod_container_resource_requests))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long-pending pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 62 },
   "targets": [
    {
     "expr": "count(sum_over_time(sum(kube_pod_status_phase{phase=\"Pending\"}) by (pod) [5m:60s]) >= 5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long-pending Resouces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource) (kube_pod_container_resource_requests * on(pod) group_left clamp_min(sum_over_time(sum(kube_pod_status_phase{phase='Pending'}) by (pod) [5m:60s]) >= 5, 1)/5)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}