{
 "title": "GKE Demo Dashboard",
 "time": { "from": "2024-02-04T09:49:12.000Z", "to": "2024-02-05T09:49:12.000Z" },
 "templating": {
  "list": [
   {
    "name": "avg_power",
    "label": "unoptimized average power consumption daily",
    "query": "58500,53500,17000"
   },
   { "name": "PUE", "label": "PUE", "query": "1.7" },
   { "name": "kwh_price", "label": "kWh price €", "query": "0.2" },
   { "name": "co2_kwh_factor", "label": "co2 kg/kWh", "query": "0.21016" },
   { "name": "pending_pods", "label": "SLO tolerated pending pods", "query": "0,1,2,3,4,5" }
  ]
 },
 "panels": [
  { "title": "DC Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Saved Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 - avg_over_time(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})[$__range:$__rate_interval])) / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DC CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})/sum(kube_node_status_allocatable{resource=\"cpu\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DC Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})/sum(kube_node_status_allocatable{resource=\"memory\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pod SLO ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "100", "legendFormat": "__auto" }
   ]
  },
  { "title": "Controller Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Resource Demand",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (resource)",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node) * on(node) (1 - sum (kube_node_spec_unschedulable) by (node)))",
     "legendFormat": "Available CPU"
    }
   ]
  },
  {
   "title": "Instant Nodes Status",
   "type": "stat",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(1 - sum (kube_node_spec_unschedulable) by (node), \"short_node\", \"$1-$2\", \"node\", \"gke-(.*)-1-default-pool-f34ee89d-(.*)\")",
     "legendFormat": "{{short_node}}"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Active Nodes"
    }
   ]
  },
  { "title": "Resource demand by resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 39 },
   "options": {
    "content": "<script>\n\n  let timeSrv = angular.element('grafana-app').injector().get('timeSrv');\n  let play_mode = false\n  let play_interval = 1\n  let reverse = false\n  const update_interval = 1000 //miliseconds!\n  \n  function play() {\n    reverse = false\n    play_mode = true\n    removeAllActiveClasses()\n    setActiveClass('btn-play')\n    console.log('play!')\n  }\n  \n  function pause() {\n    play_mode = false\n    removeAllActiveClasses()\n    setActiveClass('btn-pause')\n    console.log('pause!')\n  }\n  \n  function play_reverse() {\n    reverse = true\n    play_mode = true\n    removeAllActiveClasses()\n    setActiveClass('btn-play-rev')\n    console.log('reverse!')\n  }\n\n  // sleep time expects milliseconds\n  function sleep (time) {\n    return new Promise((resolve) => setTimeout(resolve, time));\n  }\n\n  function increaseTime() {\n    if (!play_mode) return\n    let from = timeSrv.timeRange().from\n    let to = timeSrv.timeRange().to\n\n    sleep(update_interval).then(() => {\n      if (reverse) {\n        timeSrv.setTime({from: from.add(-play_interval, 'seconds'), to: to.add(-play_interval, 'seconds')});\n      } else {\n        timeSrv.setTime({from: from.add(play_interval, 'seconds'), to: to.add(play_interval, 'seconds')});\n      }\n    });\n  }\n  \n  function removeAllActiveClasses() {\n    document.getElementById('btn-play-rev').classList.remove('btn-active')\n    document.getElementById('btn-pause').classList.remove('btn-active')\n    document.getElementById('btn-play').classList.remove('btn-active')\n  }\n\n  function setActiveClass(btn) {\n    document.getElementById(btn).classList.add('btn-active')\n  }\n  \n  window.setInterval(increaseTime, 1000)\n  \n</script>\n\n<style type=\"text/css\">\n  .btn-active {\n    background-color: #25cd93;\n  }\n  .btn-active:hover {\n    background-color: #009f77;\n  }\n</style>\n\n<div class=\"gf-form-inline\">\n  \n  <div class=\"gf-form\">\n    <button id=\"btn-play-rev\" class=\"gf-form-label gf-form-label--btn\" onclick=\"play_reverse()\"><i class=\"fa fa-backward\"></i>️</button>\n  </div>\n  <div class=\"gf-form\">\n    <button id=\"btn-pause\" class=\"gf-form-label gf-form-label--btn btn-active\" onclick=\"pause()\"><i class=\"fa fa-pause\"></i></button>\n  </div>\n  <div class=\"gf-form\">\n    <button id=\"btn-play\" class=\"gf-form-label gf-form-label--btn\" onclick=\"play()\"><i class=\"fa fa-forward\"></i></button>\n  </div>\n\n  <div class=\"gf-form\">\n    <div class=\"gf-form-label\">speed</div>\n    <div class=\"gf-form-select-wrapper\">\n      <select class=\"gf-form-input ng-pristine ng-valid ng-not-empty\" id=\"play-speed\" onchange=\"play_interval = this.options[this.selectedIndex].value\">\n        <option value=\"1\">1x</option>\n        <option value=\"5\">5x</option>\n        <option value=\"10\">10x</option>\n        <option value=\"50\">50x</option>\n        <option value=\"100\">100x</option>\n        <option value=\"500\">500x</option>\n        <option value=\"1000\">1000x</option>\n      </select>\n    </div>\n  </div>\n  \n</div>\n"
   }
  }
 ]
}