FROM registry.access.redhat.com/ubi8/ubi:latest
ENV TF_VER "2.4.4"
LABEL name="rllib-base-ubi8" \
      maintainer="danchrist@intracom-telecom.com" \
      vendor="Intracom Telecom" \
      version="1.3.0" \
      release="1" \
      summary="RLlib base utilities for Python" \
      description="RLlib base utilities for Python"

COPY licenses /licenses

### Add necessary Red Hat UBI repos here
RUN REPOLIST=ubi-8-baseos-rpms,ubi-8-appstream-rpms \
### Add your package needs here
        INSTALL_PKGS="python38 python38-devel python38-Cython curl openssh-clients openssh-server git cmake zlib-devel make gcc" && \
        dnf -y update-minimal --disableplugin=subscription-manager --setopt=tsflags=nodocs \
                --security --sec-severity=Important --sec-severity=Critical && \
        dnf -y install --disableplugin=subscription-manager --disablerepo "*" --enablerepo ${REPOLIST} --setopt=tsflags=nodocs ${INSTALL_PKGS} && \
        dnf clean all

RUN pip3 install ipython==6.0

# Install tensorflow C libs
RUN mkdir -p /tensorflow && \
        curl -fsLo /tensorflow/libtensorflow-cpu-linux-x86_64-${TF_VER}.tar.gz  https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-${TF_VER}.tar.gz && \
        cd /tensorflow && \
        tar -C /usr/local/ -xzf libtensorflow-cpu-linux-x86_64-${TF_VER}.tar.gz && \
        ldconfig && \
        rm -fr /tensorflow

# Install tensorflow && rllib
RUN pip3 install -U tensorflow==${TF_VER} && \
        pip3 install -U aioredis==1.3.1 && \
        pip3 install -U ray==1.3.0 && \
        pip3 install -U 'ray[rllib]'==1.3.0
