apiVersion: v1
kind: Pod 
metadata:
  name: pktgen-access
  labels:
    app: pktgen-access
  annotations:
    k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net1
spec:
  shareProcessNamespace: true
  nodeSelector:
    kubernetes.io/hostname: "clx1"
  containers:
  - name: access
    image: omecproject/upf-epc-bess:master-latest
    stdin: true
    tty: true
    command: ["bash", "-xc", "cp /conf/pktgen-premium-access-weekly.bess /opt/bess/bessctl/conf/; bessd -grpc-url=0.0.0.0:10514; sleep 10; ./bessctl run pktgen-premium-access-weekly"]
    resources:
      requests:
        cpu: "2000m"
        memory: "4Gi"
        hugepages-1Gi: 4Gi
        intel.com/intel_sriov_dpdk_b2b_net1: '1'
      limits:
        cpu: "2000m"
        memory: "4Gi"
        hugepages-1Gi: 4Gi
        intel.com/intel_sriov_dpdk_b2b_net1: '1'
    volumeMounts:
    - name: hugepages
      mountPath: /dev/hugepages
      readOnly: False
    - name: pattern-weekly
      mountPath: /opt/bess/bessctl/conf/patterns/
    - name: pktgen-premium-access-weekly
      mountPath: /conf
    securityContext:
      privileged: false
      capabilities:
        add:
        - IPC_LOCK
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: pattern-weekly
    configMap:
      name: pattern-weekly
      defaultMode: 0777
  - name: pktgen-premium-access-weekly
    configMap:
      name: pktgen-premium-access-weekly
      defaultMode: 0777
