apiVersion: v1
kind: Pod 
metadata:
  name: {{ .Values.access.podName | default "pktgen-access" }}
  labels:
    app: {{ .Values.access.podName | default "pktgen-access" }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
    {{- toYaml .Values.access.podAnnotations | nindent 4 }}
spec:
  shareProcessNamespace: true
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}
  containers:
  - name: {{ .Values.access.podName }}--access
    image: {{ .Values.image.repository }}
    stdin: true
    tty: true
    command: ["bash", "-xc", "cp /conf/pktgen-premium-access-weekly.bess /opt/bess/bessctl/conf/; bessd -grpc-url=0.0.0.0:10514; sleep 10; ./bessctl run pktgen-premium-access-weekly"]
    securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
    resources:
      {{- toYaml .Values.access.resources | nindent 8 }}
    volumeMounts:
      {{- toYaml .Values.access.volumeMounts | nindent 8 }}
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: pattern-weekly
    configMap:
      name: pattern-weekly
      defaultMode: 0777
  - name: pktgen-premium-access-weekly
    configMap:
      name: pktgen-premium-access-weekly
      defaultMode: 0777
