apiVersion: v1
kind: Pod 
metadata:
  name: {{ include "pktgen.fullname" . }}-access
  labels:
  {{ include "pktgen.labels" . | nindent 4 }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
    {{- toYaml .Values.access.podAnnotations | nindent 4 }}
spec:
  shareProcessNamespace: true
  serviceAccountName: {{ include "pktgen.serviceAccountName" . }}
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 6 }}
  containers:
  - name: access
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    stdin: true
    tty: true
    command: {{- toYaml .Values.access.command | nindent 6 }}
    securityContext:
    {{- toYaml .Values.securityContext | nindent 6 }}
    resources:
    {{- toYaml .Values.access.resources | nindent 6 }}
    volumeMounts:
    {{- if .Values.overideConfigMap }}
    {{- toYaml .Values.access.extraVolumeMounts | nindent 4 }}
    {{- else }}
    - name: {{ include "pktgen.fullname" . }}-access-weekly
      mountPath: /conf
    - name: {{ include "pktgen.fullname" . }}-pattern-weekly
      mountPath: /opt/bess/bessctl/conf/patterns/
    - name: hugepages
      mountPath: /dev/hugepages
    {{- end }}
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  {{- if .Values.overideConfigMap }}
  {{- toYaml .Values.access.extraVolumes | nindent 2 }}
  {{- else }}
  - name: {{ include "pktgen.fullname" . }}-pattern-weekly
    configMap:
      name: {{ include "pktgen.fullname" . }}-pattern-weekly
      defaultMode: 0777
  - name: {{ include "pktgen.fullname" . }}-access-weekly
    configMap:
      name: {{ include "pktgen.fullname" . }}-access-weekly
      defaultMode: 0777
  {{- end}}