apiVersion: v1
kind: Pod
metadata:
  name: {{ include "pktgen.fullname" . }}-core
  labels:
  {{ include "pktgen.labels" . | nindent 4 }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
    {{- toYaml .Values.core.podAnnotations | nindent 4 }}
spec:
  shareProcessNamespace: true
  nodeSelector:
  {{- toYaml .Values.nodeSelector | nindent 6 }}
  containers:
  - name: core
    image: {{ .Values.image.repository }}
    stdin: true
    tty: true
    command: {{- toYaml .Values.core.command | nindent 6 }}
    securityContext:
    {{- toYaml .Values.securityContext | nindent 6 }}
    resources:
    {{- toYaml .Values.core.resources | nindent 6 }}
    volumeMounts:
    {{- if .Values.overideConfigMap }}
    {{- toYaml .Values.core.extraVolumeMounts | nindent 4 }}
    {{- else }}
    - name: pktgen-premium-core-weekly
      mountPath: /conf
    - name: pattern-weekly
      mountPath: /opt/bess/bessctl/conf/patterns/
    - name: hugepages
      mountPath: /dev/hugepages
    {{- end }}
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  {{- if .Values.overideConfigMap }}
  {{- toYaml .Values.core.extraVolumes | nindent 2 }}
  {{- else }}
  - name: pattern-weekly
    configMap:
      name: pattern-weekly
      defaultMode: 0777
  - name: pktgen-premium-core-weekly
    configMap:
      name: pktgen-premium-core-weekly
      defaultMode: 0777
  {{- end}}