apiVersion: v1
kind: ConfigMap
metadata:
  name: premium-access-weekly
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
data:  
  pktgen-premium-access-weekly.bess: |
    """
        Access traffic (n3 receive) for premium upf 
    """

    import conf.sim as sim
    import os
    import time

    import psutil

    def get_process_affinity():
        return psutil.Process().cpu_affinity()
    
    def lines_from(file):
        lines = []
        fp = open(file, "r")
        line = fp.readline()
        while line:
            lines.append(float(line.split("\n")[0]))
            line = fp.readline()
        fp.close()
        return lines

    pkt_size = 1500
    flows = 100
    #workers=[2,4]
    #workers=[1,2]
    traffic_pattern_file = "./conf/patterns/example-large-traffic-rate-pattern.txt"
    time_step = 10 #secs
    max_load = 5000000000

    # flow create 0 ingress pattern eth / ipv4 / udp / gtpu / ipv4 / end actions rss types ipv4 l3-src-only end key_len 0 queues end / end
    n36_pkts = [sim.gen_gtpu_packet(pkt_size, "22:53:7a:15:58:50", "{{ .Values.upf.s1u }}", "11.1.1.129", "198.18.0.1", "16.0.0.1", "6.6.6.6", 0x30000000),]


    #for wid in range(len(workers)):
      #     bess.add_worker(wid=wid, core=int(workers[wid]))

    # ====================================================
    #       Core Setup
    # ====================================================


    # Initialize workers
    cores = get_process_affinity()
    workers = cores[:2]

    # set_process_affinity_all(nonworkers)
    for wid in range(len(workers)):
        bess.add_worker(wid=wid, core=int(workers[wid % len(workers)]))

    num_q = len(workers)
    kwargs = {'num_inc_q': num_q,
            'num_out_q': num_q}
    p = PMDPort(port_id=0, **kwargs)

    n3seq_kwargs = sim.gen_gtpu_sequpdate_args(flows, "16.0.0.1", 62, 0x30000000)

    src36::Source(pkt_size=pkt_size) -> Rewrite(templates=n36_pkts) -> n36update::SequentialUpdate(**n3seq_kwargs) -> L4Checksum() -> IPChecksum() -> QueueOut(port=p.name, qid=1)

    if not os.path.exists(traffic_pattern_file):
        print(f"Traffic pattern file {traffic_pattern_file} does not exist!")
        exit(1)

    lines = lines_from(traffic_pattern_file)

    if len(lines) < 1:
        print("The traffic pattern file should contain at least one traffic step.")
        exit(1)

    max_file_load = max(lines)
    bess.add_tc('36_limit', wid=1, policy='rate_limit', resource='bit', limit={'bit': int(lines[0])})
    src36.attach_task(parent='36_limit')

    while 1:
        for day in range(0,7):
            if day > 1:
                max_daily_load = max_load / 2
            else:
                max_daily_load = max_load 

            for line in lines:
                load = (line * max_daily_load) / max_file_load
                print(f"Setting current load (bits): {int(load)}")
        
                bess.update_tc_params('36_limit', resource='bit', limit={'bit': int(load)})
                bess.resume_all()
                time.sleep(time_step)

