{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "stress-ng.serviceAccountName" . }}
  labels:
    {{- include "stress-ng.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include  "stress-ng.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole }}
{{- end }}