apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omec-upf.fullname" . }}
  labels:
    {{- include "omec-upf.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "omec-upf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "omec-upf.selectorLabels" . | nindent 8 }}
    spec:
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      containers:
      - name: routectl
        image: nfvri/upf-epc-8806-bess:0.3.0-dev
        command: ["bash", "-c", "until ss -a | grep -q 3456;  do sleep 5; echo 'Waiting for bessd'; done; python /conf/route_control_premium.py -i net0 net1"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          {{- toYaml .Values.routectl.resources | nindent 12 }}
        volumeMounts:
        - name: {{ include "omec-upf.fullname" . }}-upf-conf
          mountPath: /conf
        - name: hugepages
          mountPath: /dev/hugepages
          readOnly: False
      - name: bessd
        image: nfvri/upf-epc-8806-bess:0.3.0-dev
        stdin: true
        tty: true
        command: ["bash", "-xec", "/init-conf/routes_setup.sh && bessd -grpc-url=0.0.0.0:10514; until ss -a | grep -q 10514; do sleep 5; echo waiting for bessd; done;  ./bessctl run up4_premium; ./bessctl http 0.0.0.0 3456"]
        env:
        - name: CONF_FILE
          value: /opt/bess/bessctl/conf/upf.json
        readinessProbe:
          tcpSocket:
            port: 10514
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 10514
          initialDelaySeconds: 30
          periodSeconds: 20
        securityContext:
          {{- toYaml .Values.bessd.securityContext | nindent 12 }}
        resources:
          {{- toYaml .Values.bessd.resources | nindent 12 }}
        volumeMounts:
        - name: {{ include "omec-upf.fullname" . }}-routes-setup
          mountPath: /init-conf
        - name: {{ include "omec-upf.fullname" . }}-upf-conf
          mountPath: /conf
        - name: {{ include "omec-upf.fullname" . }}-pre-install
          mountPath: /pre-install
        - name: hugepages
          mountPath: /dev/hugepages
      - name: web
        image: upf-epc-8806-bess:0.3.0-dev
        command: ["bash", "-c", "bessctl  http 0.0.0.0 8001"]
        ports:
        - name: http-web
          containerPort: 8001
          protocol: TCP
        resources:
          {{- toYaml .Values.web.resources | nindent 12 }}
      - name: pfcpiface
        image: nfvri/upf-epc-8806-pfcpiface:0.3.0-dev
        command: ["sh", "-c", "while ! $(nc -vz localhost 3456); do echo 'Waiting...'; sleep 10; done; pfcpiface -config /pre-install/upf.json -bess localhost:10514 -http 0.0.0.0:8082 -simulate create; pfcpiface -config /pre-install/upf.json"]
        volumeMounts:
        - name: {{ include "omec-upf.fullname" . }}-upf-conf
          mountPath: /conf
        - name: {{ include "omec-upf.fullname" . }}-pre-install
          mountPath: /pre-install
        ports:
        - name: http
          containerPort: 8082
          protocol: TCP
        resources:
          {{- toYaml .Values.pfcpiface.resources | nindent 12 }}
      volumes:
      - name: {{ include "omec-upf.fullname" . }}-upf-conf
        configMap:
          name: {{ include "omec-upf.fullname" . }}-upf-conf
          defaultMode: 0777
      - name: hugepages
        emptyDir:
          medium: HugePages
      - name: {{ include "omec-upf.fullname" . }}-routes-setup
        configMap:
          name: {{ include "omec-upf.fullname" . }}-routes-setup
          defaultMode: 0777
      - name: {{ include "omec-upf.fullname" . }}-pre-install 
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
