apiVersion: v1
kind: Service
metadata:
  name: {{ include "omec-upf.fullname" . }}
  labels:
    {{- include "omec-upf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http-web
      protocol: TCP
      name: http-web
  selector:
    {{- include "omec-upf.selectorLabels" . | nindent 4 }}
