apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-dpdk-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/intracom_vfio_net1
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "sriov-dpdk-net1",
  "type": "sriov",
  "trust": "on",
  "link_state": "enable"
        }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-dpdk-net2
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/intracom_vfio_net2
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "sriov-dpdk-net2",
  "type": "sriov",
  "trust": "on",
  "link_state": "enable"
 }'
