version: '3'

#networks:
#  nfvri:
#    driver: bridge
#    #name: ${NFVRI_NETWORK}

services:
  redis:
    image: redis:3.2.8
    container_name: redis-benchmark
    ports:
     - "6379:6379"
    volumes:
     - ./redis-data:/data
     - ./redis.conf:/etc/redis/redis.conf
     - ./scripts:/scripts
    command: redis-server /etc/redis/redis.conf
#    networks:
#      - nfvri

  exporter-r:
    image: bitnami/redis-exporter:latest
    container_name: exporter-r
    ports:
     - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis:6379"
    links:
     - "redis"
