apiVersion: apps/v1
kind: Deployment
metadata:
  name: pktgen
  labels:
    app: pktgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pktgen
  template:
    metadata:
      labels:
        app: pktgen
      annotations:
        k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net1,default/sriov-dpdk-b2b-net2
    spec:
      shareProcessNamespace: true
      nodeSelector:
        kubernetes.io/hostname: "clx1"
      containers:
      - name: access
        image: omecproject/upf-epc-bess:master-latest
        stdin: true
        tty: true
        command: ["bash", "-xc", "cp /conf/pktgen-premium-access-weekly.bess /opt/bess/bessctl/conf/; bessd -grpc-url=0.0.0.0:10514; ./bessctl run pktgen-premium-access-weekly"]
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
            hugepages-1Gi: 4Gi
            intel.com/intel_sriov_dpdk_b2b_net1: '1'
            intel.com/intel_sriov_dpdk_b2b_net2: '1'
          limits:
            cpu: "2000m"
            memory: "2Gi"
            hugepages-1Gi: 4Gi
            intel.com/intel_sriov_dpdk_b2b_net1: '1'
            intel.com/intel_sriov_dpdk_b2b_net2: '1'
        volumeMounts:
        - name: hugepages
          mountPath: /dev/hugepages
          readOnly: False
        - name: pattern-weekly
          mountPath: /opt/bess/bessctl/conf/patterns/
        - name: pktgen-premium-weekly
          mountPath: /conf
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      - name: core
        image: omecproject/upf-epc-bess:master-latest
        stdin: true
        tty: true
        command: ["bash", "-xc", "cp /conf/pktgen-premium-core-weekly.bess /opt/bess/bessctl/conf/; bessd -grpc-url=0.0.0.0:10514; ./bessctl run pktgen-premium-core-weekly"]
        securityContext:
          capabilities:
            add:
            - IPC_LOCK # AF_PACKET vdev (and 4K pages) uses mmap
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
            hugepages-1Gi: 4Gi
            intel.com/intel_sriov_dpdk_b2b_net1: '1'
            intel.com/intel_sriov_dpdk_b2b_net2: '1'
          limits:
            cpu: "2000m"
            memory: "2Gi"
            hugepages-1Gi: 4Gi
            intel.com/intel_sriov_dpdk_b2b_net1: '1'
            intel.com/intel_sriov_dpdk_b2b_net2: '1'
        volumeMounts:
        - name: pktgen-premium-weekly
          mountPath: /conf
        - name: pattern-weekly
          mountPath: /opt/bess/bessctl/conf/patterns/          
        - name: hugepages
          mountPath: /dev/hugepages
      volumes:
      - name: hugepages
        emptyDir:
          medium: HugePages
      - name: pattern-weekly
        configMap:
          name: pattern-weekly
          defaultMode: 0777
      - name: pktgen-premium-weekly
        configMap:
          name: pktgen-premium-weekly
          defaultMode: 0777
